### ISSUE TITLE
RPM fails to build

### ISSUE THREAD

**Issue by ChrisKozak** [serbaut/go-rpm-spec#2]
Hello,
I'm trying to use your script to package up golang 1.4.  I'm using CentOS 6.5.

The first few lines execute successfully:
sudo yum install rpmdevtools yum-utils
sudo yum-builddep go.spec
rpmdev-setuptree
spectool -R -g go.spec

However, the following line fails:
rpmbuild -bb go.spec

with the following error:
Processing files: go-debuginfo-1.4-1.el6.x86_64
error: Could not open %files file /home/vagrant/rpmbuild/BUILD/go/debugfiles.list: No such file or directory

RPM build errors:
    Could not open %files file /home/vagrant/rpmbuild/BUILD/go/debugfiles.list: No such file or directory

Does anything stand out to you immediately as being wrong?

**Comment by vladstack** [comment]
Hi Chris,
I was able to bypass this problem by adding directive to spec files:
%define debug_package %{nil}

**Comment by vladstack** [comment]
also, go 1.4.1 already out, so you can change version in specfile too.

**Comment by serbaut** [comment]
I can't reproduce this. Using centos 6.6. This is why we should use docker...

Thanks for the workaround Vlad.

**Comment by ChrisKozak** [comment]
Ok, perfect, thanks :)  I'm sending the pull request now
